apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-image
  name: nginx-image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-image
  template:
    metadata:
      labels:
        app: nginx-image
    spec:
      containers:
      - image: sesibhushan121/nginx:latest
        name: nginx-image
        imagePullPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-image
  name: nginx-svc
spec:
  ports:
  - name: nginx-svc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-image
  type: LoadBalancer
